name: Python Package using Conda

on:
    push:
      branches:
      - main
      - develop
    pull_request:
      branches:
        - main
        - develop
    schedule:
      - cron:  '0 * * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: upload file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "."
        target: "~/"
        rm: false

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: execute shell script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_ID }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script_stop: true
        script: |
          ./startup.sh
